---
apiVersion: v1
kind: Service
metadata:
  name: https-front
spec:
  type: LoadBalancer
  selector:
    app: https-front
  ports:
    - protocol: TCP
      targetPort: http
      name: http
      port: 80
    - protocol: TCP
      targetPort: https
      name: https
      port: 443
